### ISSUE TITLE
better name for the base64 variant

### ISSUE THREAD

**Issue by jerch** [jerch/base64-sixel#1]
@j4james

Since you came up with this idea - maybe you want to name it yourself?

**Comment by j4james** [comment]
It wasn't really my idea. This is just DEC's encoding format, and they refer to it as sixel encoding (look at the description of the `DECTSR` terminal state report in DEC STD-070). I don't mind what you call it, but I personally refer to it as sixel encoding.

**Comment by jerch** [comment]
Oh well - do you know by chance if that preserves the bitorder the same way base64 does?

**Comment by j4james** [comment]
I assume so, but you're in a better position to confirm than me. Just run some queries of the `DECTSR` report on your VT525 and see what it looks like. If you do two queries with a change of the cursor position in between, you should be able to see where in the report the coordinates are stored, and then confirm how those values are encoded.

I suspect it would be similar in structure to the VT320 report that was documented on the vt100.net website here:
https://vt100.net/dec/vt320/terminal_state_report

**Comment by jerch** [comment]
Well I have to check that first, seems it is not really documented in STD 070 how the 6-bit chars are constructed from 8-bit data, esp. for endianess/where bits are carried over (or I overlooked it). If thats indeed the same, then I prolly name it just "sixel encoding", with pointing to DEC as source.

**Comment by j4james** [comment]
I should say I don't think base64-sixel is a bad name either. If you're explaining it as just another base64 alphabet, that may be easier for people to understand, assuming they know what base64 is but haven't heard of sixel.

**Comment by j4james** [comment]
Actually, now that I'm reading the STD-070 documentation again, it sounds like they may only using 4 bits of each sixel anyway. See the "Implementation Guideline" referencing the VT420 implementation, where they say that bits 5 and 4 are always reset. So at least in that particular case it's not the equivalent of a base64 encoding - they're assumedly just splitting each byte into two 4-bit parts.

That's another argument in favor of naming it base64-sixel - it makes it clear that you're using a base64 encoding on top of the sixel storage format.

**Comment by jerch** [comment]
Thx for checking :heart:

**Comment by jerch** [comment]
@j4james 
Gonna go with _base64-sixel_, as it better transports its compatibility to base64 (its a simple alphabet change). Also changed some wording in the README, feel free to correct or specify things I got wrong or that are missing.

The decoder path is almost done (well scalar could see a faster lookup version still, will see about that later). Next on to encoding...
